easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Modules\Blog\Entity\BlogAuthors
        - App\Modules\Blog\Entity\BlogCategories
        - App\Modules\Blog\Entity\BlogComments
        - App\Modules\Blog\Entity\BlogPosts
