index:
    path: /
    defaults: { _controller: 'App\Modules\Blog\Controller\BlogAuthorsController::index' }
blog_posts_index:
    path: /blog/posts
    defaults: { _controller : 'App\Modules\Blog\Controller\BlogPostsController::index'}
